### ISSUE TITLE
盒模型分为哪些类型？有什么区别？

### ISSUE THREAD

**Issue by Jqianghu** [Jqianghu/interview#27]
### 2.1 盒模型的组成
 * Content: 这个区域是用来显示内容, 大小可以通过设置 width 和 height
 * Padding: 包围在内容区域外部的空白区域, 大小可以通过 padding 相关属性设置
 * Border: 边框盒包裹内容和内边距, 大小可以通过 border 相关属性设置
 * Margin: 最外面的区域, 是当前元素和其他元素之间的空白区域, 大小可以通过 margin 相关属性设置

![0715d34c98f5a80552d1e4eb9ca07b46.png](en-resource://database/5988:1)

### 2.2 标准盒模型
**设置的 width 和 height 指的是 Content**
```css
.box {
    width: 350px;
    height: 150px;
    margin: 10px;
    padding: 25px;
    border: 5px solid black;
}
/*
1. 宽度 = 350 + 25 +25 +5 + 5, 高度 = 150 + 25 + 25 + 25 + 5 +5
2. margin 不计入实际大小, 但会影响盒子实际占用空间
*/
```
![655530655a22589200206da274ba28ee.png](en-resource://database/5992:1)

### 2.3 IE盒模型
**设置的 width 和 height 包含内边距和边框**
```css
.box {
    width: 350px;
    height: 150px;
    margin: 10px;
    padding: 25px;
    border: 5px solid black;
    box-sizing: border-box; /* content-box */
    /* 浏览器默认使用标准盒模型, 要使用IE盒模型可以设置 box-sizing */
}
```
![d6e3249f8feaa809a89c43b63a09d722.png](en-resource://database/5994:1)
***
**让页面的全部元素使用IE盒模型**
```css
/* 方法1 */
* {
    box-sizing: border-box;
}
```
```css
/* 方法2 */
html {
    box-sizng: border-box;
}
*, *::before, *::after {
    box-sizing: inherit;
}
```
### 2.4 盒模型属性
**margin**
外边距会有合并现象, ...
```css
.box {
    margin: 10px;
    margin: 10px 20px; /*10px 20px 10px 20px*/
    margin: 10px 20px 30px 40px; /*上 右 下 左*/
}

.box {
margin: 0 auto; /* 0 auto 0 auto; 让块级盒子居中 */
}

.box {
    margin-top: 10px;
    margin-bottom: 20px;
    margin-left: 30px;
    margin-right: 40px;
}
```
***
**padding**
```css
.box {
    padding: 10px;
    padding: 10px 20px; /* 10px 20px 10px 20px */
    padding: 10px 20px 30px 40px; /*上 右 下 左*/
}

.box {
    padding-top: 10px;
    padding-bottom: 20px;
    padding-left: 30px;
    padding-right: 40px;
}
```
***
**border**
```css
.box {
    border: 1px solid black; /* solid, dashed, dotted */
    border-radius: 4px;
    border-radius: 50%;
}

.box {
    border-top: 10px solid #ccc;
    border-bottom: 5px dashed yellow;
    border-left: 10px solid transparent;
    border-right: 1px dotted black;
}
```
***
**width, height**
* width: 100%代表什么意思?
* height: 100% 怎么用?

```css
.box {
    width: 100px;
    height: 200px; /* 一般不需要设置 */
}
.box {
    width: 33.3%;
    widht: 100%;
    height: 100%;
}
```

### 2.5 内联盒子
**特性**
* span 的高度和宽度设置无效
* 左右外边距和左右内边距生效
* 上下外边距, 上下内边距和边框样式生效, 但不占用空间
[JSbin](http://js.jirengu.com/lofer/1/edit?html,css,output)
![75fb3a686a309767853235b07edd1b0a.png](en-resource://database/6002:1)
