### ISSUE TITLE
如何清除浮动

### ISSUE THREAD

**Issue by Jqianghu** [Jqianghu/interview#35]
**方法**
* clear: left
会使该元素移动到它前面的所有左浮元素的下方

* clear: right
会使该元素移动到它前面的所有右浮元素的下方

* clear: both
会使该元素移动到它前面的所有左浮或者右浮动元素的下方

[JSbin](http://js.jirengu.com/tudok/1/edit?html,css,output)

![833be2311cda6d904118749631499c15.png](en-resource://database/8250:0)

**消除副作用**

* 清除浮动代码
```css
.clearfix::after {
    content: '';
    display: block;
    clear: both;
}
```

* 解决副作用1: 减少对其他元素的影响
[JSbin](http://js.jirengu.com/posof/1/edit?html,css,output)

* 解决副作用2: 让父元素包裹所有浮动元素
[JSbin](http://js.jirengu.com/ruhuv/1/edit?html,css,output)

题目来自饥人谷
